# -*- coding: utf-8 -*-
"""Alekhyo Banerjee - Linspace.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15RmafCgRuPoL8RC2x91EzBmUuvp7LWvM
"""

def linspace(start,stop,division,endpoint=True,retstep=False):
    """
                   This function return evenly spaced numbers over a specified interval.
                   Date:07/02/2020
                   Created By:Alekhyo
                   Input:float/integer,float/integer,integer
                   Output:list
    """
    try:
      array=[]
      if endpoint==True:
          value_per_division=(stop-start)/(division-1)
      elif endpoint==False:
          value_per_division=(stop-start)/(division)
          
      for i in range(0,division):
          array.append(start+i*value_per_division)
      
      if retstep==True:
          print(array,"restep: ",value_per_division)
      elif retstep==False:
          print(array)
          
    except:
      print("The given division input is not an integer")

linspace(10,20,11,endpoint=False)

linspace(10,20,5,endpoint=True,retstep=True)

